### ISSUE TITLE
🐛 Tilde "~" imports in CSS not valid in all CSS pre-processors

### ISSUE THREAD

**Issue by tjosepo** [gsoft-inc/sg-orbit#1024]
## Describe the bug

The tilde "~" import used in Orbit to import styles from the `node_modules` folder is not a standard CSS feature and most CSS pre-processors do not support it.

Here's a list of how the common pre-processors handle imports in CSS:

| Preprocessor | `@import "~package";` | `@import "package";` | `@import "./relative.css";` | `url("~package")` | `url("package")`| `url("./relative.png");`
| --- | --- | --- | --- | --- | --- | --- |
| css-loader (Webpack default) | ✅ Valid | ✅ Valid | ✅ Valid | ✅ Valid | ⚠️ Requires resolve-url-loader | ⚠️ Requires resolve-url-loader
| sass-loader |  ⚠️ Marked as deprecated | ✅ Valid | ✅ Valid | ⚠️ Marked as deprecated | ⚠️ Requires resolve-url-loader | ⚠️ Requires resolve-url-loader
| postcss-loader |  ❌ Invalid | ✅ Valid | ✅ Valid | ❌ Invalid | ✅ Valid | ✅ Valid
| postcss-import (used by Vite) | ❌ Invalid | ✅ Valid | ✅ Valid | ❌ Invalid | ✅ Valid | ✅ Valid
| esbuild | ❌ Invalid | ✅ Valid | ✅ Valid | ❌ Invalid | ✅ Valid | ✅ Valid
| parcel-css | ❌ Invalid | ❌ Requires `npm:` url scheme |  ✅ Valid | ❌ Invalid | ❌ Requires `npm:` url scheme | ✅ Valid

## Potential fix

The ideal fix would be:

- Make all `@imports` relative.
- Make all `url(...)` imports relative and ask to use `resolve-url-loader`.

**Comment by alexasselin008** [comment]
After looking at this issue once again today, this could be fixed simply. 

There is 2 issues: 

## imports

We could simply change the 2 occurences of 
```diff
-@import "~@orbit-ui/css";
-@import "~@orbit-ui/components/index.css";
+@import "@orbit-ui/css";
+@import "@orbit-ui/components/index.css";
```

## url(~)

This one is trickier. We only use url(~) to position checkmarks on:
- Checkbox
- Listbox
- Menu
- Tiles

We could replace the CSS with React components that are positionned at the same place. This way we would not have to reach into assets in the node_modules.

This is the way chakra and mantine does it.
Carbon re-creates the checkmark using css instead of a mask.
