### ISSUE TITLE
Button with only an icon should have even horizontal padding

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#114]
When an icon is in a button, the button has a less prominent left padding (16px instead of 24) in order to acknowledge the icon safe space.

When an icon is alone in a button it should have a uniform horizontal padding (24px). 

![image](https://user-images.githubusercontent.com/361632/72445076-2804d100-377f-11ea-9dbd-bf0f421af3e6.png)

**Comment by fraincs** [comment]
As discussed earlier we can either introduce a property `with-single-icon` or something similar, or assume a button with only an icon shouldn't have the property `icon` set

**Comment by patricklafrance** [comment]
Not sure I like the name `with-single-icon` since we can still have a single icon event if we have text AND a single icon.

Anyway, do we really want to introduce a new class for this? We would also need to use it for circular buttons with only an icon, that would be weird.

IMO we should go with your second proposition and assume a button with only an icon shouldn't have the property `icon` set.

As far as I know this is not even something that we aim to support. If somehow a feature require this variant, I believe it's best to suggest they should use a circular button.

**Comment by fraincs** [comment]
Closing for now, until it becomes an issue
