### ISSUE TITLE
Labels should support every sizes supported by SemanticUI

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/sg-orbit#128]
### Describe the bug

Labels do not support size above large.

### Expected behavior

Support all sizes offered by Semantic including `big huge massive`

**Comment by patricklafrance** [comment]
After adding sizes to inputs I am wondering if we really want to support all the sizes available in SUI?

If these sizes doesn't make sense in our apps, why support them?

What we could do instead is throwing an "unsupported exception" if any of the unsupported sizes is specified.

What do you think?

**Comment by fraincs** [comment]
I think it's easier to support them, than having to support them down the road in a rush

**Comment by patricklafrance** [comment]
Then should we do the same for all the components? Inputs, DatePicker, MultiSelect, SearchInput, etc.. ?

I talked with Julien friday and he was telling me that we should removed the input with a height of 24px from the design system since he will never use them because they are too small.

I believe we should have a discussion with Julien before we go further with this issue.

**Comment by fraincs** [comment]
Yes, it's

**Comment by fraincs** [comment]
@patricklafrance any updates on this?

**Comment by patricklafrance** [comment]
Haven't talk to the designers.

That being said, I say we should keep what we currently have (eg. mini, tiny, small, medium & large) and release an update later if we need to support other sizes.

What do you think?

**Comment by fraincs** [comment]
Perfect let's stop at large for now, closing for the moment.
