### ISSUE TITLE
Add Github checks for Pull Requests

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#32]
The following Github checks should be considered:

**chromaticqa** 

Should be required to pass to allow a merge back to master.

Docs: https://docs.chromaticqa.com/setup_ci

**Circle CI builds**

Should be required to pass allow a merge back to master.

**Deploy storybook websites** 

Netlify deployment doesn't seem to works from PR (https://github.com/netlify/actions/issues/14).

It might work with a manual deploy, view: https://docs.netlify.com/cli/get-started/#draft-and-production-deploys

If it doesn't work, use Zeit now: https://zeit.co/docs

**Once the actions are setuped, the CI builds should be reviewed.**

**Comment by fraincs** [comment]
In order to deploy storybook websites via Netlify, we need to build Storybook, currently there is an issue when using yarn and a mono repo see : https://community.netlify.com/t/difficulty-with-new-monorepo-deployment-options/4381/3

A branch has been created in order to test this process https://github.com/gsoft-inc/sg-orbit/tree/netlify
