### ISSUE TITLE
Support Selected Value from external value instead of only defaultValue

### ISSUE THREAD

**Issue by kingbaub3** [gsoft-inc/sg-orbit#336]
### Is your feature request related to a problem?

Orbit's Select component internally manages which option is selected given its initial value and exposes a callback when the value is changed. 

![image](https://user-images.githubusercontent.com/6119223/80411530-56c03680-889a-11ea-8c96-103f318b0355.png)

This behavior works well when the Select is considered as the source of truth, but it gets tricky when integrating with another source of truth (i.e. a redux store or a backend). Let's say that the user changes the value in the select, but there is a validation error in the source of truth. In this case, the Select would display its internally managed option and not the one from the source of truth. There are no props to force it to go back to its original value.

### Describe the solution you'd like

There should be a `selectedValue` prop that forces, when provided, the Select to display the given value. That was, the selection flow of an option would go like this: 
1. The value **A** is provided as `selectedValue` and being displayed in the Select.
2. The `onChange` callback is used to listen to user intents.
3. When the user changes the value to **B**, the Select still displays **A** but the `onChange` callback is invoked.
4. In this callback, the developer can update the source of truth, no matter where it is.
5a. Upon successful validation, the source of truth is being updated and the `selectedValue` is changed to **B**, which rerenders the component and changes its displayed value to **B**. 

Alternate flow
5b. Upon failed validation, the source of truth stays the same and no rerender is needed by the Select since the value to display is still **A**.

**Comment by patricklafrance** [comment]
Thanks @kingbaub3  for the super descriptive issue, way to go!

All our components support what we call "auto controlled props". Those auto controlled props can be controlled or uncontrolled depending on whether on not you specify a value for the auto controlled prop.

A component accepting an auto controlled prop will always accept 2 props for a single auto controlled prop. A controlled prop and a default prop allowing you set the initial value when using in uncontrolled mode.

For this specific use case, the auto controlled prop that you are using is `value`. `value` props are  `value` and `defaultValue`.

Since you are specifying `defaultValue`, this is the value that will be used as the "initial" value and the prop will be considered uncontrolled, which means it will be managed by the component.

To achieve what you want, instead of `defaultValue`, use `value`.

I apologize, the documentation should highlight this way better. It will be improved someday but as you know we are short staff for the moment and must prioritize.
