### ISSUE TITLE
🌟 Update Figma-Orbit's components to match v2's specifications

### ISSUE THREAD

**Issue by GateNk** [gsoft-inc/sg-orbit#560]
## Description

To ensure that no old components are used in current and future Mockups, it is crucial that they should be updated to meet our newest established specs.

https://sg-storybook.netlify.app/

## Checklist

- [x] Colors
- [x] Shadows
- [x] Spacing
- [x] Typography
- [x] Accordion
- [x] Alert
- [x] Badge
- [x] Button
- [x] Checkbox
- [x] Counter
- [x] CrossButton
- [x] Divider
- [x] Dot
- [x] Input (Text, TextArea, Number, Date, DateRange)
- [x] Link
- [x] Listbox
- [x] Lozenge
- [x] Menu
- [x] Popover
- [x] Radio
- [x] Select
- [x] Switch
- [x] Tabs
- [x] Tag
- [x] Tooltip

**Comment by patricklafrance** [comment]
🥇 🥇 🥇 

How can I get those Figma links? I could add them to our documentation:

![image](https://user-images.githubusercontent.com/794579/117187130-95d87000-ada9-11eb-99eb-5a226d5f9ba1.png)

**Comment by patricklafrance** [comment]
Since this card is not yet done... we added a new content option to the `<Tag>` component! It's now possible to specify an "end icon". 

An end icon should only be used to add a list of icons. We basically added end icon to enable the following use case:

![image](https://user-images.githubusercontent.com/794579/117187658-2616b500-adaa-11eb-9647-1a896cb9feab.png)

More info available here https://github.com/gsoft-inc/sg-orbit/issues/589

The official documentation for end icon is available [here](https://orbit.sharegate.design/?path=/docs/tag--default-story#end-icon).
