### ISSUE TITLE
🐛 Documentation: Icon Button should not specify default shape and use ButtonGroup instead of inline

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#587]
## Describe the bug
https://orbit.sharegate.design/?path=/docs/button--default-story#icon-button

In this example, the property shape="circular" should not be specified since its the default value. This code might get copy pasted and we don't want add too many useless props.

Also, this page has 10 usage of Inline, should they all be ButtonGroup? I know its not technically a button group since they are not related to each other, but it may improve adoption of the button group component if people are used to see it

**Comment by patricklafrance** [comment]
I do agree for `shape="circular"` but not for using `<ButtonGroup>` instead of `<Inline>`. The document use cases are not expected use cases for a `<ButtonGroup>`

**Comment by alexasselin008** [comment]
All good with me

**Comment by alexasselin008** [comment]
My concern was that if we decide some components are internal only, like inline and flex, i would prefer seeing a div with classnames rather than an inline component that is not documented

**Comment by patricklafrance** [comment]
I understand but these internal components are not documented. What is not documented is not available. We do have a few custom components for documentation purpose only that are also not documented. What's the difference between those and `<Inline>` ?

To me the difference is that you know `<Inline>` is an actual component exported by the react-components package because you are an Orbit contributor ;)
