### ISSUE TITLE
🐛 Autocomplete: Items do not accept nested children

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/sg-orbit#592]
When using Autocomplete, the `selection.value` does not take into account `Text` elements that are nested in a child.

## Describe the bug

Children of `Item` used in `Autocomplete` are not considered as `value`.

## Steps to reproduce

Create an Autocomplete with ReactNode children (like in Apricot, using <UserDisplay>). The `selection` param in `onChange` is returning an empty value, even if the `UserDisplay` component has a `Text` element.

## Expected results

The value of the `selection` param should be filled with the content of the `Text` component of `UserDisplay`.

**Comment by patricklafrance** [comment]
An autocomplete value must be something that can be set as an [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) value. Input value only accept string value.

**Comment by alexasselin008** [comment]
The value can be a string with the name of the user or it's id, this is not the issue.

We should be able to render our items the way we want. 

There are a couple of type of fixes we could do here : 
1- Have item accept a "value" prop instead of parsing it's children property to find the value
2- the autocomplete uses an internal method getItemText that could be overwritten via a prop so we can customize it. 

Otherwise, what alternative would you suggest to cover our people picker use cases?

 
![image](https://user-images.githubusercontent.com/38871812/117145686-657cdb80-ad81-11eb-9e6a-543996eae29e.png)
![image](https://user-images.githubusercontent.com/38871812/117145702-6b72bc80-ad81-11eb-9ad9-34c75347d8a7.png)
![image](https://user-images.githubusercontent.com/38871812/117145737-775e7e80-ad81-11eb-85a9-0105dd5b1790.png)
![image](https://user-images.githubusercontent.com/38871812/117145789-86453100-ad81-11eb-812f-26e3cc83da3d.png)
![image](https://user-images.githubusercontent.com/38871812/117145805-8b09e500-ad81-11eb-92ac-494f4a42cec2.png)
![image](https://user-images.githubusercontent.com/38871812/117145816-90672f80-ad81-11eb-83b1-17b3b1b35ae9.png)
![image](https://user-images.githubusercontent.com/38871812/117145850-98bf6a80-ad81-11eb-9b4f-9c8c6e0bb4f6.png)

**Comment by alexasselin008** [comment]
A good example of what i mean is that we have example in orbit of select accepting an icon. The icon is not part of the value, but is part of the item's look. 

https://orbit.sharegate.design/?path=/docs/select--default-story#item-end-icon

**Comment by patricklafrance** [comment]
Well no, you shouldn't be able to render wathever you want. This is the whole idea of a DS to think about what we need and offer pre-determined template to easily render standardize UI.

I don't see the issue here. If you look at the avatar exemple [in the following section](https://orbit.sharegate.design/?path=/docs/autocomplete--default-story#item-description) it's exactly what you need.

With the following code

```
<Autocomplete placeholder="Planets" aria-label="Planets" onChange={(event, selection) => { console.log(selection); }}>
    <Item key="earth">
        <Avatar slot="avatar">ER</Avatar>
        <Text>Earth</Text>
        <Text slot="description">Home sweet home!</Text>
    </Item>
    <Item key="jupiter">
        <Avatar slot="avatar">JU</Avatar>
        <Text>Jupiter</Text>
        <Text slot="description">The fourth-brightest object in the sky</Text>
    </Item>
    <Item key="mars">
        <Avatar slot="avatar">MA</Avatar>
        <Text>Mars</Text>
        <Text slot="description">See you in 2026</Text>
    </Item>
</Autocomplete>
```

You get the following console log when you select a value:

```
{key: "earth", value: "Earth"}
{key: "mars", value: "Mars"}
```

**Comment by alexasselin008** [comment]
We've had a discussion in a Teams call and the takeway are : 

- We don't want to allow rendering anything in the items. We want to try and standardize everything
- Even if we have a UserDisplay component that renders a photo / name / description, we should "duplicate" that logic and make an item with UserPhoto("avatar")/Text/Text("description").
