### ISSUE TITLE
🐛 A tag start icon & dot should have right margin when fluid

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#595]
## Describe the bug

When a tag render as fluid, a start icon or a dot doesn't have a right margin. It generally render fine but not when the space is constraint:

![image](https://user-images.githubusercontent.com/794579/117184398-af2bed00-ada6-11eb-90e6-9a5e630e73a0.png)

One of the major concern with starting content is to ensure the text is always aligned if we have 2 vertical tags (which doesn't work right now):

![image](https://user-images.githubusercontent.com/794579/117184731-0cc03980-ada7-11eb-8fe2-fdffb049193e.png)

A solution could be to always reserve starting space when a tag is fluid. If there is an icon or dot, it would be rendering in this space, if there is none, the space would still be reserved.

**Comment by fraincs** [comment]
This will require some changes to the way we treat a dot inside a tag, nothing out of the ordinary, since we can't know for sure if the fluid Tag could contain an icon or a dot, we need to make sure a dot and an icon occupy the same space in order to reserve space for either of those.

I suggest centering a dot in a 20x20 box. This would make sure the reserved space is the same.
