### ISSUE TITLE
🐛 Padding issue in Disclosure

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#600]
## Describe the bug

When there is a Checkbox group inside a disclosure, the left side of the checkboxes get cropped when expanding and collapsing the disclosure

## Steps to reproduce

![disclosure](https://user-images.githubusercontent.com/38871812/117493191-a66f1e80-af40-11eb-8edf-49a5dbe1d3d1.gif)

## Expected results

The checkbox's left side should not be cropped

## Reproducible demo

In the documentation : 

```
<Disclosure>
    <Button>Privacy Setting</Button>
    <Box>
      <CheckboxGroup orientation="vertical" gap={4}>
          <Checkbox value="milky-way">Private</Checkbox>
          <Checkbox value="andromeda">Public</Checkbox>
      </CheckboxGroup>
    </Box>
</Disclosure>
```

**Comment by patricklafrance** [comment]
@fraincs can you have a look please?

**Comment by fraincs** [comment]
> @fraincs can you have a look please?
> 
> Alex have a workaround by specfiying `<Box className="ml1">` but I would prefer if he doesn't have to do this.

The problem is not with the Disclosure Per Se but due to the fact that the Checbbox are made with box shadow who are not adds to the dimensions of an element, a focused element would have the same problem. One way to solve this is to shift everything in a disclosure but we can't for sure assume what's inside and by how much it will overflow. 

@patricklafrance

**Comment by patricklafrance** [comment]
It's not easy to see but on Alex's gif but the problem seems to be with the left border of a checkbox. I am not sure what you're saying apply for this case?

Here's another gif:

![checkbox_disclosure](https://user-images.githubusercontent.com/794579/117497570-aa05a400-af46-11eb-8406-b34e5ab1db40.gif)
