### ISSUE TITLE
❗ Add Hex code to the colors in the documentation

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#660]
## Description

Add Hex value in the Colors section of the documentation. In the figma models, we often only have the hex colors without it's name. Its harder now to find those color in the documentation, since they are under the hsla format.

**Comment by fraincs** [comment]
I think this would add a layer of complexity as we use only HSLA and Figma supports HSL, which is the same as HSLA but without an alpha. Why don't we try to have all Figma colours use the named colour, especially since we are moving toward semantic colours anyway and this would become a bigger problem.

**Comment by fraincs** [comment]
@alexasselin008

**Comment by patricklafrance** [comment]
Have we been able to add the colour named to Figma?
