### ISSUE TITLE
❗  Add label position to fields or forms

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#700]
## Description

We have some cases of forms that are inline. It would be nice if the forms or fields would allow a labelposition="left" props 

![image](https://user-images.githubusercontent.com/38871812/124148568-c19c6d00-da5d-11eb-9289-21cfbe5a90ed.png)

Example in spectrum : 
https://react-spectrum.adobe.com/react-spectrum/Form.html#visual-options

**Comment by patricklafrance** [comment]
Spectrum is doing it this way because it's the input which render the label. Since with Orbit you have total control over the rendering/placement of the Label component you should be able to handle this yourself.

That being said, of course then making sure the space between the label and the input fall in the end of the developer, which is never good from a standardization standpoint. But as far as I know, this type of field design is something that is not standard nor supported by Orbit. I am not sure what is the right answer here.

We could at some point offer layout support for this kind of thing, I am not sure in which form though.

**Comment by alexasselin008** [comment]
I believe that it would be the Field component's job to allow positionning of the label to the left. 

"A field add a label and a message to an input. They are typically used in forms and dialogs."

Since a field have a grid layout for labels and message, if i want to allow left positionning, i would have to overwrite the grid template. I don't have issues doing this, but it seems like something that could be added in this component

**Comment by patricklafrance** [comment]
Got it, yes sorry you're right the Field component could provide the layout.

Still, I am not sure if we want to officially support this style of layout for a field. I'll keep this request open and write back here when I have more info on our stance about this.

Thanks for the idea.

**Comment by patricklafrance** [comment]
Still waiting for design.

**Comment by fraincs** [comment]
Will poke the designers to see if it's still a need and if it can be documented.

**Comment by patricklafrance** [comment]
Did design came up with something @fraincs ?

**Comment by fraincs** [comment]
Will need to plan a talk with them.
