### ISSUE TITLE
❗ Badge should allow different background colors

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/sg-orbit#862]
## Description

When rendering a Badge with the Dot variant. The idea is to quickly indicate to the user that something new is available. However, the gray "hard-break" color doesn't seem an appropriate color to capture the user's attention. We should be able to customize the
dot color, or have a set of defined colors we can use.

Exemple : 
```
        <ToggleIconButton aria-label="Whats News" variant="tertiary">
          <Badge slot="icon" variant="dot" overlap="icon">
            <NotificationIcon />
          </Badge>
        </ToggleIconButton>
```
![image](https://user-images.githubusercontent.com/38871812/148952561-7c045716-6518-46b5-8357-04bcbde12c42.png)
![image](https://user-images.githubusercontent.com/38871812/148952573-f0a9376f-11de-4b1b-a312-bc1b4097ab80.png)

**Comment by fraincs** [comment]
Something to keep in mind is that a badge can contain text, in order to keep a good contrast we should limit the options or it can lead to some accessibility issues.

**Comment by patricklafrance** [comment]
Badges used to be red to get the user attention but it's been updated to gray with the new DA. Maybe the solution is not to make the backgroundColor customizable but instead bring this issue to the designers and ask for a new color?

I am not sure what use cases would required to have customizable backgroundColor for badges. IMO, the issue here might just be that the current backgroundColor is not the right one. The badge backgroundColor should be standardize accross an app.

If we do want to allow custom backgroundColor then there are a few options...

The rendered HTML is the following:

```
<div class="o-ui-badge o-ui-badge-dot o-ui-badge-over-circle o-ui-html-div">
        <div class="o-ui-badge-anchor o-ui-html-div"></div>
        <div class="o-ui-html-div"></div>
</div>
```

Right now we will render the additional props (e.g styling props) on the outer element with the `o-ui-badge` class. Which is as expected. What we want is to have a way to provide style props to the inner element with the `o-ui-badge-anchor` class.

1- The obvious one is to forward the backgroundColor prop (and maybe the color prop) to the inner component. It would work but I ususally don't like forwarding specific props. Things could get messy and hard to understand from a consumer standpoint. I tend to move away from this when there are alternative solutions.

2- We could update the Badge component to always receive as children the actual badge component AND the component to anchor to. It's already happenning for an icon badge and kind of happening for a text badge. The only one which is not is the dot variant. The dot variant could receive a Dot component.

```
<Badge>
    <Text>100</Text>
    <Square />
</Badge>
<Badge variant="dot">
    <Dot backgroundColor="red" />
    <Square />
</Badge>
<Badge variant="icon">
     <CheckCircleIcon />
      <Square />
</Badge>
```

3- Another solution, which might in fact be the best one IMO would be to do like the TextInput component and add a `wrapperProps.` We could forward all the Badge props to the inner component (e.g. the dot in your case) and the `wrapperProps` would be rendered on the outer element (the one with the `o-ui-badge` class).

**Comment by patricklafrance** [comment]
Oh and there is a 4) one! Almost forgot.

We could do something similar to Chakra `colorScheme` https://chakra-ui.com/docs/data-display/badge#badge-color (we would have to find another name though).

This solution might be in par with the @fraincs warning about color contrast since Orbit would keep the ownership of the colors.

I still believe a badge color shouldn't be customizable though... but if we have to, I think 3) and 4) could be a good options.

In fact, even if we don't change anything, I would do 3), it should have been done from day 1.

**Comment by GateNk** [comment]
We've agreed one using Background Accent (+ Static White for the font) as the new color for our badges.

We can't justify as of yet the need for multiple colors. You can look at these small tests we did: https://www.figma.com/proto/3x1wJC9LVl2vrREjBMk6Jp/Untitled?page-id=0%3A1&node-id=3%3A124737&viewport=398%2C48%2C0.21&scaling=min-zoom&starting-point-node-id=3%3A121477 (You can click anywhere on the page to browse through the 4 options for either mode)
