### ISSUE TITLE
🐛 Weird press effect on mobile when clicking on a button

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#879]
## Describe the bug

When on mobile, there is an additional effect when I click (well press since im on mobile) on a button. The additional effect is the dark gray background color. I don't see this on desktop. I guess it's a press effect specific to mobile?

Here's what it looks like on an Accordion:

https://user-images.githubusercontent.com/794579/150363936-75a64762-21f4-4f8e-86ca-99631d0ebb0f.mp4

**Comment by fraincs** [comment]
This is iOS way to let you know you tapped something and something will happen, usually a page load. I am not against removing it, but this is the why here. I wonder if we are not removing a default behaviour without giving an alternative hint, some people uses javascript to fade out tapped items to 50% opacity, in order to let the user know the user the button has been tapped and that we’re loading the next page, an action is happening.

**Comment by fraincs** [comment]
I just checked and Android adds a tap highlight too, it's blue and non distracting, I would lean toward not removing these as these are accessibility features.

**Comment by patricklafrance** [comment]
@fraincs I agree! I wonder though if we should run this by the designers. Maybe they could suggest a few changes to our UI to accomodate those behaviors.

**Comment by fraincs** [comment]
@patricklafrance will do some digging with my iPad to see what's the consensus.

**Comment by fraincs** [comment]
Should we unify the tap highlight color between ios and android? ios being a kinda gray and android being a blue.

**Comment by fraincs** [comment]
Upon discussions with the designers we decided not to unify and keep the colors the way the user expect them per OS (iOs / Android).
